# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/toolformer',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/toolformer',
                'lib_path': 'toolformer'},
  'syms': { 'toolformer.api': { 'toolformer.api.APIBase': ('api.html#apibase', 'toolformer/api.py'),
                                'toolformer.api.APIBase.__call__': ('api.html#apibase.__call__', 'toolformer/api.py'),
                                'toolformer.api.APIBase.__init__': ('api.html#apibase.__init__', 'toolformer/api.py'),
                                'toolformer.api.execute_calculator': ('api.html#execute_calculator', 'toolformer/api.py')},
            'toolformer.data_generator': { 'toolformer.data_generator.DataGenerator': ( 'data_generator.html#datagenerator',
                                                                                        'toolformer/data_generator.py'),
                                           'toolformer.data_generator.DataGenerator.__init__': ( 'data_generator.html#datagenerator.__init__',
                                                                                                 'toolformer/data_generator.py'),
                                           'toolformer.data_generator.DataGenerator.generate': ( 'data_generator.html#datagenerator.generate',
                                                                                                 'toolformer/data_generator.py')},
            'toolformer.prompt': {},
            'toolformer.utils': {'toolformer.utils.yaml2dict': ('utils.html#yaml2dict', 'toolformer/utils.py')}}}
