# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/toolformer',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/toolformer',
                'lib_path': 'toolformer'},
  'syms': {'toolformer.api': {'toolformer.api.execute_calculator': ('api.html#execute_calculator', 'toolformer/api.py')}}}
