# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_api.ipynb.

# %% auto 0
__all__ = ['execute_calculator']

# %% ../nbs/03_api.ipynb 5
def execute_calculator(expr):
    try:
        return eval(expr)
    except:
        return ""
