# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_api.ipynb.

# %% auto 0
__all__ = ['BaseAPI', 'execute_calculator']

# %% ../nbs/03_api.ipynb 4
from typing import Callable

# %% ../nbs/03_api.ipynb 6
class BaseAPI:
    def __init__(self, func: Callable):
        self.func = func
    
    def __call__(self, *args: str, **kargs: str) -> str:
        return self.func(*args, **kargs)

# %% ../nbs/03_api.ipynb 8
def execute_calculator(expr):
    try:
        return eval(expr)
    except:
        return ""
